name: finance_banking_app_ui
description: 'A new Flutter project.'
publish_to: 'none'
version: 1.0.0+1
environment:
    sdk: '>=3.2.5 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    google_fonts: ^6.1.0
    flutter_svg: ^2.0.9
    slide_to_confirm: ^1.1.0

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true
    assets:
        - assets/icons/
        - assets/images/
        - assets/svg/
    fonts:
        - family: nav_drawer
          fonts:
              - asset: assets/icons/nav_drawer.ttf
        - family: slide_icon
          fonts:
              - asset: assets/icons/slide_icon.ttf
